sudo: required

services:
  - docker

before_install:
  - docker build -t "$DOCKER_ID"/react-complex-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run  "$DOCKER_ID"/react-complex-test npm run test -- --coverage

after_success:
  - docker build -t "$DOCKER_ID"/multi-client ./client
  - docker build -t "$DOCKER_ID"/multi-nginx  ./nginx
  - docker build -t "$DOCKER_ID"/multi-server ./server
  - docker build -t "$DOCKER_ID"/multi-worker ./worker
  - docker ps -a 
  - docker images "DOCKER_ID"/
  - echo "$DOCKER_ID" 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  - docker push "$DOCKER_ID"/multi-client 
  - docker push "$DOCKER_ID"/multi-nginx 
  - docker push "$DOCKER_ID"/multi-server 
  - docker push "$DOCKER_ID"/multi-worker

 
