sudo: required
services:
  - docker

before_install:
  - docker build -t manjunathhr/react-complex-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run  manjunathhr/react-complex-test npm run test -- --coverage

after_success:
  - docker build -t manjunathhr/multi-client ./client
  - docker build -t manjunathhr/multi-nginx  ./nginx
  - docker build -t manjunathhr/multi-server ./server
  - docker build -t manjunathhr/multi-worker ./worker
  - docker ps -a 
  - docker images "DOCKER_ID"/
  - echo "$DOCKER_ID" 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  - docker push manjunathhr/multi-client 
  - docker push manjunathhr/multi-nginx 
  - docker push manjunathhr/multi-server 
  - docker push manjunathhr/multi-worker

 